FROM node:20-slim
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /srv

# copy the configuration files first to cache dependencies
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages ./packages
# Copy all app package.json files to ensure the workspace is valid
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/
# COPY apps/docs/package.json ./apps/docs/

# Install ALL dependencies (including devDependencies like tsx/nodemon)
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# the source code will be mount via Docker Compose volumes.

EXPOSE 3012 3013 3014

# a generic CMD that can be override in docker-compose
CMD ["pnpm", "dev"]
