packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  "zod": "4.3.6"
catalogs:
 fastify:
   "fastify": "5.7.4"
 fastify_util:
   "fastify-type-provider-zod": "6.1.0"
 http_client:
   "got": "14.6.6"
   "axios": "1.15.2"
 database:
   "mongodb": "7.1.0"


enablePrePostScripts: true


