export const gitDeploymentSteps = [
	"Validating Git repository URL",
	"Authenticating with provider",
	"Provisioning isolated build environment",
	"Initializing Git submodules",
	"Cloning source code from remote",
	"Checking out commit SHA",
	"Analyzing repository structure",
	"Detecting runtime and framework versions",
	"Injecting environment variables",
	"Restoring dependency cache",
	"Installing project dependencies",
	"Running pre-build hooks",
	"Compiling source code and assets",
	"Optimizing production build",
	"Saving dependency cache for future builds",
	"Running static analysis and linting",
	"Scanning for security vulnerabilities",
	"Generating OCI-compliant container image",
	"Compressing build artifacts",
	"Uploading image to private registry",
	"Verifying image integrity",
	"Terminating build environment",
	"Provisioning runtime resources",
	"Configuring internal networking and service mesh",
	"Attaching persistent storage volumes",
	"Pulling container image to compute nodes",
	"Starting application instances",
	"Initializing log streaming",
	"Performing readiness and liveness probes",
	"Configuring edge network and load balancer",
	"Updating DNS records",
	"Issuing/Renewing SSL certificates",
	"Commencing canary traffic shift",
	"Monitoring error rates and latency",
	"Scaling up new deployment instances",
	"Decommissioning legacy instances",
	"Deployment successfully finalized",
];

export const zipDeploymentSteps = [
	"Receiving archive stream",
	"Verifying upload integrity (Checksum validation)",
	"Scanning archive for malware and malicious signatures",
	"Validating archive format and compression headers",
	"Provisioning isolated extraction environment",
	"Decompressing archive contents",
	"Checking for illegal symlinks and path traversal attempts",
	"Calculating extracted directory size against quotas",
	"Identifying project entry point",
	"Detecting runtime environment (Node.js, Python, Go, etc.)",
	"Validating manifest files (package.json, requirements.txt, etc.)",
	"Injecting environment variables and secrets",
	"Initializing dependency resolution",
	"Restoring build cache from previous uploads",
	"Installing project dependencies",
	"Pruning development-only dependencies",
	"Running pre-build scripts",
	"Compiling source code and transpiling assets",
	"Optimizing production bundles",
	"Performing static security analysis (SAST)",
	"Creating OCI-compliant container layer",
	"Compressing final build artifacts",
	"Uploading build image to internal registry",
	"Cleaning up temporary extraction files",
	"Verifying container image readiness",
	"Allocating runtime compute resources",
	"Configuring virtual networking and port mapping",
	"Mounting persistent storage and config maps",
	"Pulling production image to target nodes",
	"Starting application process",
	"Attaching log stream buffers",
	"Executing readiness and liveness health checks",
	"Updating load balancer target groups",
	"Applying SSL/TLS termination rules",
	"Redirecting traffic to new deployment",
	"Monitoring initial request telemetry",
	"Purging edge cache (CDN)",
	"Deployment successfully completed",
];
